In [1]:
import numpy as np
data = np.genfromtxt('classification.csv', delimiter=',')

In [2]:
data = np.genfromtxt('classification.csv', delimiter=',', skip_header = 1) # загружаю данные

In [3]:
data

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [5]:
TP = 0 # True positive, класс относится к 1 и мы его отнесли к 1
FP = 0 # False positive, класс относится к 0 а мы его отнесли к 1
FN = 0 # False positive, класс относится к 1 а мы его отнесли к 0
TN = 0 # True negative, класс относится к 0 и мы его отнесли к 0

In [15]:
# расчет

TP = 0 
FP = 0
FN = 0 
TN = 0
for i in range(len(data)):
    if data[i,0] == data[i,1] and data[i,0] == 1:
        TP += 1
    if data[i,0] == data[i,1] and data[i,0] == 0:
        TN += 1
    if data[i,0] != data[i,1] and data[i,0] == 1:
        FN += 1
    if data[i,0] != data[i,1] and data[i,0] == 0:
        FP += 1

In [16]:
print('TP ' + str(TP))
print('TN ' + str(TN))
print('FN ' + str(FN))
print('FP ' + str(FP))

TP 43
TN 64
FN 59
FP 34


In [20]:
from sklearn.metrics import accuracy_score


In [21]:
# доля верно угаданных, посчитали библиотекой
a = accuracy_score(data[:, 0], data[:, 1])

In [22]:
a

0.535

In [23]:
# доля верно угаданных посчитали вручную
accuracy = (TP + TN) / (TP + TN + FN + FP)

In [24]:
accuracy

0.535

In [25]:
# точность, посчитали вручную
precision = TP / (TP+FP)
precision

0.5584415584415584

In [26]:
# точность посчитали библиотекой
from sklearn.metrics import precision_score
p = precision_score(data[:, 0], data[:, 1])
p

0.5584415584415584

In [27]:
# полнота, поситали вручную
recall = TP / (TP+FN)

In [28]:
recall

0.4215686274509804

In [29]:
# полнота, посчитали библитотекой
from sklearn.metrics import recall_score
r = recall_score(data[:, 0], data[:, 1])
r

0.4215686274509804

In [30]:
# f-мера, посчитали библиотекой
from sklearn.metrics import f1_score
f= f1_score(data[:, 0], data[:, 1])
f

0.48044692737430167

In [31]:
# f-мера, посчитали вручную
fm = 2*recall*precision/ (recall + precision)

In [32]:
fm

0.48044692737430167

In [33]:
# загрузили данные для второго задания
data_curves = np.genfromtxt('scores.csv', delimiter=',', skip_header = 1)

In [34]:
data_curves

array([[ 0.00000000e+00,  6.83832312e-01,  1.45975892e-01,
         7.87062520e-01,  5.00000000e-01],
       [ 1.00000000e+00,  8.01966493e-01,  2.39511362e-01,
         1.00000000e+00,  8.33333333e-01],
       [ 0.00000000e+00,  3.82315363e-01, -2.45700629e-01,
         0.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  5.06796890e-01, -1.37058453e-01,
         0.00000000e+00,  1.05263158e-01],
       [ 1.00000000e+00,  4.88781485e-01, -1.54148428e-01,
         0.00000000e+00,  1.05263158e-01],
       [ 0.00000000e+00,  1.08506238e-01, -7.90863950e-01,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  4.13748983e-01, -1.85142546e-01,
         2.83052507e-01,  3.63636364e-01],
       [ 0.00000000e+00,  9.61081256e-01,  8.30973225e-01,
         1.00000000e+00,  1.00000000e+00],
       [ 0.00000000e+00,  5.57326069e-02, -8.72805158e-01,
         0.00000000e+00,  1.00000000e-01],
       [ 0.00000000e+00,  1.68708121e-01, -5.18390389e-01,
         0.00000000e+00

In [35]:
from sklearn.metrics import roc_auc_score

In [36]:
# площадь под ROC-кривой для классификатора, чем она больше, тем больше точность алгоритма
score_logreg = roc_auc_score(data_curves[:, 0], data_curves[:, 1])
score_logreg

0.719187675070028

In [37]:
# площадь под ROC-кривой для классификатора, чем она больше, тем больше точность алгоритма
SVM = roc_auc_score(data_curves[:, 0], data_curves[:, 2])
SVM 

0.7086834733893557

In [38]:
# площадь под ROC-кривой для классификатора, чем она больше, тем больше точность алгоритма
score_knn = roc_auc_score(data_curves[:, 0], data_curves[:, 3])
score_knn 

0.6351540616246498

In [39]:
# площадь под ROC-кривой для классификатора, чем она больше, тем больше точность алгоритма
score_tree = roc_auc_score(data_curves[:, 0], data_curves[:, 4])
score_tree 

0.6919267707082833

In [40]:
from sklearn.metrics import precision_recall_curve

In [41]:
# Какой классификатор достигает наибольшей точности (Precision) при полноте (Recall) не менее 70% ?

# Чтобы получить ответ на этот вопрос, 
# найдите все точки precision-recall-кривой с помощью функции sklearn.metrics.precision_recall_curve. 
# Она возвращает три массива: precision, recall, thresholds. 
# В них записаны точность и полнота при определенных порогах, указанных в массиве thresholds. 
# Найдите максимальной значение точности среди тех записей, для которых полнота не меньше, чем 0.7.

p_score_logreg, r_score_logreg, t_score_logreg = precision_recall_curve(data_curves[:, 0], data_curves[:, 1])

In [42]:
p_score_logreg

array([0.49746193, 0.49489796, 0.49230769, 0.49484536, 0.49740933,
       0.49479167, 0.4973822 , 0.49473684, 0.4973545 , 0.5       ,
       0.5026738 , 0.5       , 0.4972973 , 0.5       , 0.50273224,
       0.50549451, 0.50828729, 0.51111111, 0.51396648, 0.51685393,
       0.51977401, 0.52272727, 0.52571429, 0.52873563, 0.53179191,
       0.53488372, 0.5380117 , 0.53529412, 0.53846154, 0.54166667,
       0.54491018, 0.54819277, 0.55151515, 0.54878049, 0.55214724,
       0.54938272, 0.55279503, 0.55625   , 0.55974843, 0.55696203,
       0.56050955, 0.56410256, 0.56129032, 0.56493506, 0.56862745,
       0.56578947, 0.56953642, 0.56666667, 0.5704698 , 0.57432432,
       0.57142857, 0.57534247, 0.57241379, 0.57638889, 0.58041958,
       0.58450704, 0.58156028, 0.58571429, 0.58992806, 0.58695652,
       0.59124088, 0.59558824, 0.6       , 0.59701493, 0.60150376,
       0.60606061, 0.60305344, 0.6       , 0.60465116, 0.609375  ,
       0.61417323, 0.61111111, 0.616     , 0.62096774, 0.62601

In [43]:
r_score_logreg

array([1.        , 0.98979592, 0.97959184, 0.97959184, 0.97959184,
       0.96938776, 0.96938776, 0.95918367, 0.95918367, 0.95918367,
       0.95918367, 0.94897959, 0.93877551, 0.93877551, 0.93877551,
       0.93877551, 0.93877551, 0.93877551, 0.93877551, 0.93877551,
       0.93877551, 0.93877551, 0.93877551, 0.93877551, 0.93877551,
       0.93877551, 0.93877551, 0.92857143, 0.92857143, 0.92857143,
       0.92857143, 0.92857143, 0.92857143, 0.91836735, 0.91836735,
       0.90816327, 0.90816327, 0.90816327, 0.90816327, 0.89795918,
       0.89795918, 0.89795918, 0.8877551 , 0.8877551 , 0.8877551 ,
       0.87755102, 0.87755102, 0.86734694, 0.86734694, 0.86734694,
       0.85714286, 0.85714286, 0.84693878, 0.84693878, 0.84693878,
       0.84693878, 0.83673469, 0.83673469, 0.83673469, 0.82653061,
       0.82653061, 0.82653061, 0.82653061, 0.81632653, 0.81632653,
       0.81632653, 0.80612245, 0.79591837, 0.79591837, 0.79591837,
       0.79591837, 0.78571429, 0.78571429, 0.78571429, 0.78571

array([0.07073872, 0.07492334, 0.08668825, 0.09673339, 0.10160274,
       0.10850624, 0.11765768, 0.13781334, 0.1387966 , 0.13961478,
       0.15190177, 0.15200061, 0.15733163, 0.15876748, 0.16073298,
       0.1615582 , 0.16654799, 0.16870812, 0.173184  , 0.17884898,
       0.18570984, 0.19601518, 0.21195512, 0.21235997, 0.21360642,
       0.2177899 , 0.2281761 , 0.23908033, 0.25524525, 0.25935972,
       0.26019936, 0.27141442, 0.27419836, 0.27559374, 0.27591229,
       0.27647238, 0.28207412, 0.28255693, 0.28297781, 0.29683666,
       0.29957253, 0.30069636, 0.30578731, 0.31066455, 0.31212154,
       0.31391685, 0.3142305 , 0.32071136, 0.32251018, 0.3304837 ,
       0.3435888 , 0.3452384 , 0.35819307, 0.36018868, 0.36661136,
       0.36969124, 0.37385575, 0.38231536, 0.38520436, 0.39172819,
       0.40863332, 0.41374898, 0.41758012, 0.42145995, 0.42459981,
       0.42553822, 0.42802822, 0.43658125, 0.43795397, 0.44154691,
       0.44660932, 0.45395143, 0.45726078, 0.46825773, 0.47043

In [45]:
# ищем максимальную точность, с полнотой не менее 70% 
p_score_logreg_max =0 
for i in range(len(p_score_logreg)):
    if r_score_logreg[i] >= 0.7:
        if p_score_logreg[i] > p_score_logreg_max:
            p_score_logreg_max = p_score_logreg[i]

In [46]:
p_score_logreg_max

0.6302521008403361

In [47]:
p_SVM, r_SVM, t_SVM = precision_recall_curve(data_curves[:, 0], data_curves[:, 2])

In [48]:
p_SVM_max =0 
for i in range(len(p_SVM)):
    if r_SVM[i] >= 0.7:
        if p_SVM[i] > p_SVM_max:
            p_SVM_max = p_SVM[i]
p_SVM_max

0.6228070175438597

In [49]:
p_score_knn, r_score_knn, t_score_knn = precision_recall_curve(data_curves[:, 0], data_curves[:, 3])

In [50]:
p_score_knn_max =0 
for i in range(len(p_score_knn)):
    if r_score_knn[i] >= 0.7:
        if p_score_knn[i] > p_score_knn_max:
            p_score_knn_max = p_score_knn[i]
p_score_knn_max

0.6065573770491803

In [51]:
p_score_tree, r_score_tree, t_score_tree = precision_recall_curve(data_curves[:, 0], data_curves[:, 4])

In [52]:
p_score_tree_max =0 
for i in range(len(p_score_tree)):
    if r_score_tree[i] >= 0.7:
        if p_score_tree[i] > p_score_tree_max:
            p_score_tree_max = p_score_tree[i]
p_score_tree_max

0.6517857142857143